### ISSUE TITLE
Installing `hein` for replicating FinalNtb.ipynb

### ISSUE THREAD

**Issue by ppope** [stat-ml/GeoMLE#5]
How can we install the `hein` package for replicating the results in `FinalNtb.ipynb`?

https://github.com/stat-ml/GeoMLE/blob/master/paper/FinalNtb.ipynb?short_path=25aa346#L51-L52

**Comment by Tismoney** [comment]
Sorry for the omission.

The official code you can find [here](https://www.ml.uni-saarland.de/code/IntDim/IntDim.htm). Notice that you need only one main cpp file.

**Comment by ppope** [comment]
Great! Many thanks for your expedient reply
